; ==========================================
; WATT VISION - MODULO IOT
; ESP32 + PZEM-004T V3.0
; ==========================================

[env:esp32dev]

; Plataforma e placa
platform = espressif32
board = esp32dev
framework = arduino

; Monitor serial
monitor_speed = 115200

; Sistema de arquivos existente
board_build.filesystem = littlefs

; Bibliotecas
lib_deps =
    mandulaj/PZEM-004T-v30
    knolleary/PubSubClient